[program:x11vnc]
command=/usr/local/bin/x11vnc-wrapper.sh
autostart=true
autorestart=true
startsecs=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisord/x11vnc
redirect_stderr=true

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 0.0.0.0:6080 127.0.0.1:5900
autostart=true
autorestart=true
startsecs=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisord/novnc
redirect_stderr=true
